question_data = [
        {
            "category": "Entertainment: Video Games",
            "difficulty": "medium",
            "question": "Nintendo started out as a playing card manufacturer.",
            "correct_answer": "True",
        },
        {
            "category": "Science & Nature",
            "difficulty": "medium",
            "question": "The Neanderthals were a direct ancestor of modern humans.",
            "correct_answer": "False",
        },
        {
            "category": "Science & Nature",
            "difficulty": "medium",
            "question": "A person can get sunburned on a cloudy day.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "easy",
            "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "easy",
            "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
            "correct_answer": "False",
        },
        {
            "category": "Geography",
            "difficulty": "easy",
            "question": "Vatican City is a country.",
            "correct_answer": "True",
        },
        {
            "category": "Geography",
            "difficulty": "easy",
            "question": "San Marino is the only country completely surrounded by another country.",
            "correct_answer": "False",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "hard",
            "question": "Unturned originally started as a Roblox game.",
            "correct_answer": "True",
        },
        {
            "category": "Sports",
            "difficulty": "medium",
            "question": "Soccer player Cristiano Ronaldo opened a museum dedicated to himself.",
            "correct_answer": "True",
        },
        {
            "category": "Science & Nature",
            "difficulty": "medium",
            "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "medium",
            "question": "The first Maxis game to feature the fictional language 'Simlish' was The Sims (2000).",
            "correct_answer": "False",
        },
        {
            "category": "Science & Nature",
            "difficulty": "medium",
            "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
            "correct_answer": "False",
        },
        {
            "category": "Vehicles",
            "difficulty": "medium",
            "question": "The Chevrolet Corvette has always been made exclusively with V8 engines only.",
            "correct_answer": "False",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "easy",
            "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
            "correct_answer": "True",
        },
        {
            "category": "Science: Gadgets",
            "difficulty": "easy",
            "question": "The communication protocol NFC stands for Near-Field Control.",
            "correct_answer": "False",
        },
        {
            "category": "Geography",
            "difficulty": "medium",
            "question": "Vietnam is the only country in the world that starts with V.",
            "correct_answer": "False",
        },
        {
            "category": "Science: Computers",
            "difficulty": "medium",
            "question": "MacOS is based on Linux.",
            "correct_answer": "False",
        },
        {
            "category": "Politics",
            "difficulty": "easy",
            "question": "Denmark has a monarch.",
            "correct_answer": "True",
        },
        {
            "category": "Science & Nature",
            "difficulty": "medium",
            "question": "Scientists accidentally killed the once known world's oldest living creature, a mollusc, known to be aged as 507 years old.",
            "correct_answer": "True",
        },
        {
            "category": "Science: Computers",
            "difficulty": "medium",
            "question": "The open source program Redis is a relational database server.",
            "correct_answer": "False",
        },
        {
            "category": "Entertainment: Music",
            "difficulty": "easy",
            "question": "The alternative rock band, They Might Be Giants, released their album 'Flood' in 1990. ",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Books",
            "difficulty": "easy",
            "question": "'Elementary, my dear Watson' is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "difficulty": "hard",
            "question": "Throughout the entirety of 'Dragon Ball Z', Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Film",
            "difficulty": "hard",
            "question": "'Cube', 'Cube 2: Hypercube' and 'Cube Zero' were directed by the same person.",
            "correct_answer": "False",
        },
        {
            "category": "Entertainment: Music",
            "difficulty": "medium",
            "question": "'Twenty One Pilots' made the song 'The Motion' featuring Sampha.",
            "correct_answer": "False",
        },
        {
            "category": "Geography",
            "difficulty": "hard",
            "question": "Switzerland has four national languages, English being one of them.",
            "correct_answer": "False",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "easy",
            "question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
            "correct_answer": "True",
        },
        {
            "category": "Vehicles",
            "difficulty": "medium",
            "question": "Bugatti was an Italian car manufacturer.",
            "correct_answer": "False",
        },
        {
            "category": "Science: Computers",
            "difficulty": "medium",
            "question": "It's not possible to format a write-protected DVD-R Hard Disk.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "easy",
            "question": "In 'Undertale', the main character of the game is Sans.",
            "correct_answer": "False",
        },
        {
            "category": "Animals",
            "difficulty": "easy",
            "question": "Cats have whiskers under their legs.",
            "correct_answer": "True",
        },
        {
            "category": "History",
            "difficulty": "easy",
            "question": "In World War II, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy/D-day landing.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Cartoon & Animations",
            "difficulty": "medium",
            "question": "Nickelodeon rejected the pilot to Adventure Time.",
            "correct_answer": "True",
        },
        {
            "category": "Geography",
            "difficulty": "medium",
            "question": "Norway has a larger land area than Sweden.",
            "correct_answer": "False",
        },
        {
            "category": "Politics",
            "difficulty": "hard",
            "question": "Nazi Germany surrendered on Harry Truman's birthday while he was president.",
            "correct_answer": "True",
        },
        {
            "category": "History",
            "difficulty": "easy",
            "question": "Kublai Khan is the grandchild of Genghis Khan?",
            "correct_answer": "True",
        },
        {
            "category": "Animals",
            "difficulty": "easy",
            "question": "The Killer Whale is considered a type of dolphin.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "medium",
            "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
            "correct_answer": "True",
        },
        {
            "category": "History",
            "difficulty": "hard",
            "question": "During the Winter War, the amount of Soviet Union soliders that died or went missing was five times more than Finland's.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Television",
            "difficulty": "medium",
            "question": "An episode of 'The Simpsons' is dedicated to Moe Szyslak's bar rag.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Books",
            "difficulty": "easy",
            "question": "'Green Eggs and Ham' consists of only 50 different words.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "easy",
            "question": "In 'Need for Speed: Porsche Unleashed', the player can only drive cars manufactured by Porsche.",
            "correct_answer": "True",
        },
        {
            "category": "Science & Nature",
            "difficulty": "easy",
            "question": "Water always boils at 100°C, 212°F, 373.15K, no matter where you are.",
            "correct_answer": "False",
        },
        {
            "category": "Geography",
            "difficulty": "easy",
            "question": "There is an island in Japan called \u014ckunoshima, A.K.A. 'Rabbit Island', so named because of it's huge population of rabbits.",
            "correct_answer": "True",
        },
        {
            "category": "General Knowledge",
            "difficulty": "easy",
            "question": "A pasodoble is a type of Italian pasta sauce.",
            "correct_answer": "False",
        },
        {
            "category": "General Knowledge",
            "difficulty": "medium",
            "question": "'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.' is a grammatically correct sentence.",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "hard",
            "question": "In 'Minecraft', gold tools are faster than diamond tools.",
            "correct_answer": "True",
        },
        {
            "category": "Science: Computers",
            "difficulty": "easy",
            "question": "The Python programming language gets its name from the British comedy group 'Monty Python.'",
            "correct_answer": "True",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "easy",
            "question": "Each piece in Tetris is called a tetris.",
            "correct_answer": "False",
        },
        {
            "category": "Entertainment: Video Games",
            "difficulty": "hard",
            "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man's Tree.",
            "correct_answer": "True",
        }
    ]
