"""A container module for all dry data"""


# Exit code legend:
#   code 0: The program quit succesfully
#   code 1: The program quit unexpectedly or is currently running and logged in

settings = {
    "exit_code": 0,
    "language": "english"
}


coding_words = {
    "a": ["a", "A", "4", "@"],
    "b": ["b", "B", "8"],
    "c": ["c", "C"],
    "d": ["d", "D"],
    "e": ["e", "E", "3"],
    "f": ["f", "F"],
    "g": ["g", "G"],
    "h": ["h", "H"],
    "i": ["i", "I", "1", "!"],
    "j": ["j", "J"],
    "k": ["k", "K"],
    "l": ["l", "L", "1"],
    "m": ["m", "M"],
    "n": ["n", "N"],
    "o": ["o", "O", "0"],
    "p": ["p", "P"],
    "q": ["q", "Q"],
    "r": ["r", "R"],
    "s": ["s", "S", "5", "$"],
    "t": ["t", "T", "7"],
    "u": ["u", "U"],
    "v": ["v", "V"],
    "w": ["w", "W"],
    "x": ["x", "X"],
    "y": ["y", "Y"],
    "z": ["z", "Z"]
}

RANDOM_WORDS = {
    "adjectives": (
        "abaft", "abject", "aggressive", "aback", "absent", "acidic", "arrogant", "awful", "assorted", "ambitious",
        "abnormal", "auspicious", "ambiguous", "agreeable", "administrative", "aromatic", "aboard", "aspiring",
        "additional", "average", "accessible", "ad hoc", "adventurous", "amuck", "alleged", "absurd", "apathetic",
        "aboriginal", "accurate", "amusing", "abashed", "abandoned", "axiomatic", "adjoining", "automatic", "ashamed",
        "awesome", "abrasive", "alert", "angry", "abiding", "aware", "acid", "adaptable", "actually", "ablaze",
        "accidental", "adhesive", "aberrant", "alive",
        "blushing", "basic", "befitting", "broken", "bouncy", "belligerent", "blurry", "black", "bright", "blue",
        "boundless", "bizarre", "boring", "berserk", "boiling", "bored", "bloody", "best", "breakable", "bashful",
        "busy", "barbarous", "bawdy", "bitter", "brash", "bustling", "billowy", "breezy", "broad", "brainy", "bumpy",
        "boorish", "brown", "brave", "better", "bossy", "bewildered", "beneficial", "bad", "beautiful",
        "burly", "brief", "bulky", "brawny", "bent", "big",
        "colorful", "cloudy", "cut", "ceaseless", "curvy", "calm", "classy", "coordinated", "colossal", "civil",
        "cautious", "clear", "concerned", "caring", "crazy", "certain", "complex", "chemical", "calculating",
        "combative", "charming", "changeable", "clammy", "cagey", "crooked", "cruel", "consistent", "craven",
        "cultural", "callous", "chief", "chunky", "cool", "cute", "common", "cloistered", "critical", "chivalrous",
        "cooing", "childlike", "cynical", "creepy", "coherent", "capable", "cooperative", "cumbersome", "comfortable",
        "confident", "competitive", "chilly",
        "damaged", "dependent", "dull", "dramatic", "dangerous", "decorous", "desperate", "difficult", "dashing",
        "deranged", "descriptive", "dry", "dispensable", "discreet", "defiant", "deeply", "domineering", "decent",
        "doubtful", "defective", "different", "daily", "diligent", "disgusted", "distinct", "draconian", "dead",
        "direful", "deafening", "depressed", "delightful", "drab", "dysfunctional", "daffy", "dear", "disillusioned",
        "defeated", "deserted", "damaging", "disagreeable", "delicious", "decisive", "disastrous", "determined",
        "drunk", "disturbed", "dynamic", "dizzy", "dazzling", "delirious", "digital", "democratic", "dirty", "discreet",
        "dominant", "diplomatic",
        "encouraging", "exclusive", "economic", "edgy", "evil", "efficient", "early", "erect", "excellent", "entire",
        "exuberant", "eager", "exotic", "ethereal", "earsplitting", "enchanted", "erratic", "exultant", "environmental",
        "every", "equal", "elated", "eight", "entertaining", "eminent", "educational", "electric", "endurable",
        "elastic", "expensive", "eccentric", "earthy", "emotional", "elegant", "easy", "evasive", "existing",
        "efficacious", "even", "electronic", "envious", "eastern", "equable", "evanescent", "enormous", "elite",
        "elderly", "exciting", "enchanting", "energetic", "ethnic", "extended", "executive", "explicit", "eternal",
        "elusive", "eerie",
        "fearful", "federal", "frail", "flowery", "finicky", "fanatical", "future", "foreign", "famous", "female",
        "feigned", "four", "frantic", "faint", "fresh", "faithful", "fluttering", "flashy", "free", "flagrant",
        "fluffy", "first", "flat", "fabulous", "filthy", "fat", "full", "faded", "fast", "former", "fearless",
        "frequent", "false", "fertile", "foregoing", "flippant", "fallacious", "fair", "foamy", "furtive", "fancy",
        "few", "fantastic", "far", "fretful", "fine", "flimsy", "fuzzy", "festive", "freezing", "funny", "flat",
        "graceful", "grotesque", "great", "giddy", "guarded", "global", "grey", "gray", "gusty", "glistening",
        "glamorous", "good", "gruesome", "glorious", "grieving", "gratis", "gifted", "guttural", "guiltless", "gamy",
        "grumpy", "godly", "grubby", "grandiose", "glossy", "gigantic", "gainful", "gaudy", "gullible", "greedy",
        "glib", "gabby", "giant", "grateful", "green", "greasy", "garrulous", "general", "guilty", "gaping", "gleaming",
        "groovy", "gorgeous", "goofy", "grouchy", "gentle", "green", "grateful",
        "healthy", "helpful", "hulking", "heartbreaking", "harsh", "hypnotic", "hideous", "halting", "horrible", "hurt",
        "humorous", "harmonious", "heavy", "humdrum", "handsomely", "homeless", "half", "heavenly", "handsome",
        "hysterical", "hushed", "highfalutin", "hesitant", "happy", "high", "hallowed", "husky", "hapless",
        "historical", "hilarious", "hurried", "homely", "handy", "honorable", "hospitable", "helpless", "hateful",
        "habitual", "hellish", "hard", "holistic", "hissing", "huge", "hollow", "hot", "hungry",
        "hanging", "heady", "hypothesized", "honest",
        "impossible", "inquisitive", "incredible", "imported", "idle", "impartial", "infamous", "irritating",
        "impolite", "illegal", "imminent", "itchy", "ignorant", "informal", "industrious", "incompetent", "innate",
        "icy", "inner", "imperfect", "invincible", "impressive", "interesting", "inconclusive", "illustrious",
        "incandescent", "insidious", "instinctive", "ill", "intelligent", "internal", "imaginary", "irate", "immense",
        "innocent", "icky", "impatient", "immediate", "important", "inexpensive", "idiotic", "invisible",
        "incentive", "inappropriate", "indirect",
        "joyous", "judicious", "juicy", "jaded", "juvenile", "jazzy", "jealous", "jittery", "jagged", "jumpy", "jolly",
        "jobless", "jumbled", "judgmental", "junior", "jolting", "jumping", "judicial",
        "kaput", "keen", "knowing", "knotty", "known", "kind", "kindhearted", "knightly",
        "latter", "logical", "likeable", "lewd", "low", "loving", "left", "luxuriant", "last", "lazy", "limping",
        "lying", "legal", "lucky", "lopsided", "lonely", "ludicrous", "languid", "lean", "lowly", "labored", "lavish",
        "laughable", "lyrical", "long", "lacking", "lush", "lively", "loutish", "literate", "lame", "learned", "large",
        "light", "lamentable", "loose", "lethal", "lackadaisical", "lumpy", "late", "longing", "loud", "like", "lovely",
        "little", "living", "loose", "linear",
        "maniacal", "majestic", "misty", "macabre", "moldy", "murky", "mysterious", "marvelous", "mammoth", "married",
        "marked", "magical", "maddening", "motionless", "mindless", "moaning", "material", "makeshift", "mental",
        "magnificent", "many", "military", "mundane", "massive", "male", "magenta", "messy", "mighty", "medical",
        "meek", "materialistic", "madly", "mute", "mean", "mixed", "minor", "meaty", "malicious", "measly", "mere",
        "macho", "mature", "mushy", "miniature", "miscreant", "milky", "merciful", "melted", "mountainous", "momentous",
        "medieval", "modest",
        "naughty", "nutritious", "nosy", "nostalgic", "nebulous", "nippy", "neighborly", "noxious", "nutty", "nice",
        "normal", "needy", "nonstop", "near", "noisy", "nervous", "nifty", "nauseating", "new", "nine", "next",
        "numberless", "nimble", "nondescript", "nonchalant", "nasty", "neat", "narrow", "necessary", "noiseless",
        "natural", "nappy", "naive", "null", "numerous", "needless", "negative", "noble",
        "odd", "outstanding", "optimal", "omniscient", "overwrought", "obtainable", "obscure", "obedient", "old",
        "offbeat", "obviously", "obsequious", "ordinary", "onerous", "outrageous", "opposite", "overrated", "ossified",
        "organic", "obese", "obsolete", "one", "obeisant", "oval", "oafish", "open", "obnoxious", "orange", "oceanic",
        "observant", "overjoyed", "overconfident", "obvious", "outgoing", "overt", "obscene",
        "panoramic", "piquant", "premium", "profuse", "pink", "proud", "pastoral", "powerful", "pleasant", "physical",
        "purple", "painful", "parsimonious", "polite", "psychedelic", "placid", "past", "plastic", "pointless", "poor",
        "practical", "pricey", "pumped", "plant", "parched", "present", "plausible", "pregnant", "pushy", "productive",
        "puzzling", "painstaking", "periodic", "psychological", "popular", "parallel", "precious", "permissible",
        "pure", "private", "poised", "pathetic", "probable", "puffy", "petite", "picayune", "pale", "protective",
        "prickly", "political", "perfect", "professional", "pour",
        "quickest", "questionable", "quaint", "quiet", "quizzical", "quick", "quack", "quarrelsome", "quirky",
        "quixotic",
        "rainy", "receptive", "roomy", "right", "responsible", "rambunctious", "relieved", "rebel", "repulsive",
        "reflective", "rampant", "rapid", "red", "righteous", "ruddy", "realistic", "round", "resolute", "redundant",
        "ratty", "robust", "rightful", "raspy", "rabid", "royal", "romantic", "rough", "rhetorical", "ritzy",
        "recondite", "ready", "roasted", "reasonable", "real", "regular", "rude", "relevant", "rustic", "rigid", "rare",
        "rural", "rich", "racial", "ripe", "rotten", "resonant", "recent", "reminiscent", "ragged", "remarkable",
        "rare", "radical",
        "spotted", "scary", "scared", "separate", "shocking", "sexual", "sweltering", "statuesque", "simplistic",
        "suspicious", "secretive", "sincere", "spotless", "subsequent", "swanky", "simple", "seemly", "sore", "salty",
        "sassy", "sloppy", "shut", "square", "spicy", "shrill", "scrawny", "smart", "selfish", "subdued", "stiff",
        "smoggy", "serious", "synonymous", "splendid", "sparkling", "strong", "sick", "snotty", "sad", "swift",
        "selective", "spiky", "symptomatic", "stale", "sophisticated", "strict", "skinny", "superb", "slow",
        "scientific", "sensitive",
        "thankful", "tired", "three", "tranquil", "tight", "two", "thoughtful", "tricky", "tremendous", "taboo",
        "truthful", "teeny", "truculent", "tangible", "tame", "tawdry", "tense", "tender", "terrific", "ten",
        "toothsome", "thirsty", "thinkable", "tasty", "tearful", "third", "tacit", "thin", "tan", "talented",
        "temporary", "tangy", "tasteless", "threatening", "tiny", "tedious", "tenuous", "thoughtless", "tall", "tough",
        "therapeutic", "terrible", "testy", "towering", "tacky", "tiresome", "tart", "typical", "trite", "trashy",
        "thick",
        "unwieldy", "ultra", "untidy", "unsuitable", "unknown", "unhappy", "utter", "useless", "unhealthy", "unfair",
        "used", "uninterested", "unaccountable", "unusual", "unsightly", "unable", "unruly", "undesirable", "unlikely",
        "unequal", "ugly", "unused", "utopian", "unequaled", "upbeat", "united", "upset", "uptight", "uppity",
        "unbecoming", "unbiased", "uneven", "unarmed", "uttermost", "unkempt", "ugliest", "unique", "useful",
        "understood", "unnatural", "ubiquitous", "unadvised", "unwritten", "uncovered",
        "violet", "venomous", "vigorous", "verdant", "victorious", "vacuous", "vagabond", "various", "voiceless",
        "versed", "volatile", "vast", "vivacious", "vengeful", "visible", "vague", "valuable", "violent", "voracious",
        "vulgar", "virtual",
        "windy", "white", "weak", "warm", "wooden", "wet", "watery", "weary", "woebegone", "wasteful", "warlike",
        "womanly", "whole", "wakeful", "waiting", "wiggly", "whimsical", "worthless", "willing", "wistful", "wicked",
        "wretched", "wealthy", "wary", "waggish", "wanting", "witty", "wimpy", "wild", "wandering", "wrong",
        "wacky", "wise", "wholesale", "wry", "wrathful", "wiry", "wonderful", "whispering", "workable", "woozy",
        "worried", "wide",
        "xenon", "xenial",
        "young", "yellow", "youthful", "yummy"
    ),
    "nouns": (
        "agency", "attitude", "advertising", "analysis", "appearance", "association", "agreement", "affair",
        "assistance", "army", "airport", "administration", "alcohol", "addition", "article", "artisan", "audience",
        "assistant", "atmosphere", "ability", "assignment", "anxiety", "apple", "application", "assumption", "advice",
        "area", "awareness", "art", "argument", "analyst", "arrival", "aspect", "attention", "actor", "activity",
        "accident", "appointment", "ambition", "apartment",
        "bonus", "birthday", "baseball", "bread", "bathroom", "bird", "breath", "beer", "bath", "basis", "bedroom",
        "buyer", "boyfriend", "basket", "blood", "breakdown", "boom", "bulb", "barrier", "bracket", "bottle", "beat",
        "budget", "boot", "buffet", "base", "body", "battery", "button", "bike", "brand", "battlefield", "Bible",
        "broccoli", "biography", "bridge", "belly", "blast", "bi",
        "championship", "collection", "category", "cheek", "cookie", "control", "college", "cell", "community",
        "courage", "cigarette", "climate", "confusion", "concept", "camera", "contribution", "country", "chocolate",
        "charity", "client", "customer", "consequence", "coffee", "childhood", "candidate", "classroom", "chemistry",
        "chapter", "child", "criticism", "clothes", "city", "cousin", "committee", "contract", "communication",
        "cabinet", "combination", "conclusion", "connection", "comparison", "complaint", "currency", "computer",
        "chest", "conversation", "cancer", "construction", "celebration", "church",
        "device", "distribution", "dirt", "dad", "drawing", "department", "depth", "dealer", "decision", "discussion",
        "desk", "debt", "difficulty", "direction", "diamond", "drawer", "disaster", "definition", "death", "database",
        "driver", "depression", "departure", "disease", "development", "difference", "description", "dinner",
        "director", "disk", "data", "drama", "delivery", "dorm", "decoration", "denial", "designer", "discipline",
        "drug", "duck", "dome", "directory", "dependence", "disturbance", "detector", "doll", "disagreement", "deck",
        "dairy", "dog", "dress", "daughter", "diagram", "dollar", "dinner",
        "energy", "efficiency", "engineering", "estate", "effort", "exam", "explanation", "elevator", "event",
        "employee", "error", "ear", "equipment", "entertainment", "emphasis", "employment", "environment", "education",
        "employer", "excitement", "economics", "extent", "establishment", "examination", "editor", "emotion",
        "enthusiasm", "election", "entry", "expression", "engine", "exception", "education", "electron", "economist",
        "essay", "extraterrestrial", "enthusiast", "ego", "elite", "explosion", "exemption", "end", "exploration",
        "excavation", "engagement", "example", "equation", "experience",
        "finding", "funeral", "foundation", "fishing", "fact", "family", "failure", "flight", "fortune", "farmer",
        "food", "feedback", "friendship", "freedom", "football", "folklore", "frame", "fabric", "flavor", "feather",
        "function", "fireplace", "funeral", "fan", "feast", "fisherman", "fuss", "franchise", "foot", "flag", "force",
        "feminist", "fraction", "forecast",  "frequency", "fashion", "fame", "file",
        "girl", "guidance", "guest", "guitar", "grocery", "gene", "girlfriend", "growth", "garbage", "government",
        "gate", "grandmother", "goal", "glass", "gear", "glue", "gravity", "grain", "governor", "graphic",  "garage",
        "grudge", "goal", "guitar", "gown", "girlfriend", "gradient", "grace", "guerrilla", "glow", "gold", "gas",
        "generation", "grave", "ghost", "goat", "gift", "glove", "gossip", "gate", "government",
        "hall", "hotel", "health", "historian", "hospital", "hat", "height", "homework", "hearing", "housing", "heart",
        "honey", "hair", "highway", "history", "hate", "hook", "helmet", "hostage", "hike", "hardware", "hole",
        "heaven", "highlight", "hemisphere", "honor", "harbor", "hip", "hand", "hit", "housewife", "horizon", "head",
        "holiday", "humanity", "history", "height", "hostility", "horseshoe", "hiccup", "hypothesis", "hay", "horror",
        "hell", "houseplant", "haircut", "hunter",
        "intention", "investment", "importance", "insurance", "income", "injury", "inspector", "industry",
        "improvement", "indication", "initiative", "inspection", "interaction", "imagination", "instance", "inflation",
        "independence", "insect", "internet", "information", "impression", "instruction", "introduction", "idea",
        "item", "ideology", "invasion", "implication", "investigation", "innovation", "invention", "irony", "illusion",
        "infection", "insight", "invite", "integration", "issue", "impulse", "inspiration", "integrity", "interference",
        "influence", "institution", "image",
        "judgment",  "jewel", "jukebox", "jealousy", "jack", "justice", "jigsaw", "jockstrap", "jumper", "jumbals",
        "jacal", "jarble", "javeline", "jady", "jedi", "joystick", "jury",  "joy", "joint", "jacket", "jelly", "joke",
        "journal", "jurisdiction", "jail", "jet", "job", "jaw", "jungle", "jam", "judge", "jest",
        "knowledge", "king", "kickdown", "knob", "key", "kite", "knee", "kick", "killer", "kitchen", "kit", "kidney",
        "knot", "knit", "kettle", "kid", "knife", "kitten", "kiwi", "karate", "keyboard", "koala", "keeper", "khaki",
        "kernel", "kamikadze",
        "location", "ladder", "love", "language", "lake", "loss", "leadership", "library", "leader", "length", "lab",
        "literature", "law", "lady", "license", "liability", "layout", "lane", "lung", "linen", "lunch", "laboratory",
        "laser", "land", "letter", "leftovers", "lemon", "lighter", "lip", "leadership", "layer",
        "membership", "medicine", "meat", "method", "month", "mode", "movie", "management", "memory", "media",
        "meaning", "midnight", "marriage", "music", "manager", "mud", "marketing", "menu", "measurement", "map",
        "magazine", "mall", "maintenance", "math", "moment", "manufacturer", "mixture", "member", "message", "meal",
        "mood", "mom", "model", "moon", "mushroom", "movement", "medal", "mind", "man", "magnitude", "morale", "misery",
        "minister", "Mars", "mayor", "mail", "machinery", "makeup", "mist", "maze",
        "night", "negotiation", "newspaper", "nature", "news", "nation", "nitwit", "nitro", "nail", "node", "noise",
        "nest", "novel", "name", "nightmare", "neighbour", "nose", "note", "notebook", "nerve", "necklace", "nonsense",
        "network", "notice", "needle", "number", "net", "nap", "neck", "navy",
        "organization", "orange", "office", "opinion", "oven", "opportunity", "owner", "obligation", "outcome",
        "operation", "occasion", "outlet", "outline", "oil", "overview", "outfit", "obstacle", "organisation", "owl",
        "opponent", "objective", "option", "observer",
        "police", "problem", "professor", "priority", "philosophy", "policy", "perspective", "patience", "passenger",
        "percentage", "presentation", "painting", "poet", "player", "protection", "possibility", "pizza", "pollution",
        "product", "preference", "population", "pie", "platform", "proposal", "poetry", "permission", "possession",
        "personality", "preparation", "promotion", "procedure", "psychology", "person", "potato", "paper", "phone",
        "property", "people", "piano", "politics", "photo", "power", "perception", "profession", "passion", "payment",
        "presence", "physics", "performance", "poem", "profile", "picture", "panel", "pill", "partner", "plan", "pupil",
        "photography", "potential",
        "queen", "quantity", "quality", "qualification", "quotation", "quote", "question", "quest", "queue",
        "reflection", "ratio", "replacement", "reality", "response", "reading", "refrigerator", "revenue", "resolution",
        "reaction", "recording", "reputation", "relationship", "revolution", "requirement", "reception", "river",
        "role", "relation", "region", "restaurant", "resource", "recognition", "responsibility", "recipe", "republic",
        "road", "recommendation", "rule", "rice", "recruit", "revival", "resort", "reproduction", "researcher",
        "review", "rifle", "rhythm", "rumor", "radio", "reporter",
        "sector", "sample", "soup", "song", "salad", "significance", "story", "skill", "storage", "satisfaction",
        "supermarket", "student", "stranger", "steak", "situation", "solution", "son", "series", "speaker", "security",
        "system", "scene", "surgery", "session", "sister", "safety", "society", "secretary", "shopping", "strategy",
        "science", "software", "studio", "signature", "statement", "speech", "selection", "sympathy", "suggestion",
        "setting", "shirt", "sir", "success", "singer", "source", "settlement", "sweater", "slogan", "state", "swarm",
        "stereotype", "swing", "snake", "sand", "soul", "shorts", "star", "soldier", "symptom", "sickness", "space",
        "sleeve",
        "theory", "teacher", "tale", "town", "thing", "teaching", "tension", "tennis", "truth", "television", "throat",
        "temperature", "tooth", "topic", "trainer", "two", "thanks", "thought", "tradition", "transportation", "tea",
        "technology", "tongue", "tetris", "terrace", "trace", "taxi", "tone", "toast", "tube", "trust", "torture",
        "tribe", "theft", "trench", "tablet", "tank", "trip", "telephone", "team", "thread",
        "unit", "uncle", "user", "understanding", "union", "university", "uncertainty", "urge", "umbrella", "urine",
        "unity", "uvula",
        "variety", "virus", "video", "volume", "variation", "version", "village", "vehicle", "victim", "veteran",
        "vitamin", "voxel", "volcano", "vocabulary", "viscosity", "vibration", "villa", "vest", "verb", "vehicle",
        "value", "vegetable", "violation", "voyage", "victory", "volunteer", "Venus", "ventriloquist", "vegetation",
        "vacuum", "view", "vision", "voice", "vessel", "variable", "version", "veil", "vote", "virgin", "vain", "van",
        "valley", "voucher", "vegetarian",
        "woman", "wealth", "writer", "world", "writing", "winner", "worker", "week", "weakness", "wife", "wedding",
        "warning", "way", "wood", "wolf", "wrestler", "waste", "wreck", "weapon", "wave", "whip", "wage", "will",
        "wrap", "warrant", "wonder", "waterfall", "water", "wind", "wrist", "wire", "winter", "wheel", "weed",
        "workshop", "witch", "worm", "wagon", "work", "window", "witness",
        "xenon", "xeon", "xantia", "xara", "xenia", "xerox",
        "yard", "youth", "year", "yardstick", "yarn", "yeti", "yoga", "yogourt",
        "zero", "zone", "zebra", "zombie", "zenith"
    )
}
